# Generated by Django 3.2.4 on 2021-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
                ('music_name', models.CharField(max_length=200)),
                ('love', models.PositiveSmallIntegerField()),
                ('enjoy', models.PositiveSmallIntegerField()),
                ('sentimental', models.PositiveSmallIntegerField()),
                ('sad', models.PositiveSmallIntegerField()),
                ('stressed', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
